<a href="https://colab.research.google.com/github/CarlosBaztan/Clases-Python-UNIR/blob/main/Clase3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#Definimos la primera función
def auditar_ventas(lista_ventas): #La función se llama auditar_ventas y tiene una incógnita que es lista_ventas
  alertas = 0 #Se inicializa en 0 porque es donde vamos a ir acumulando la suma
  for venta in lista_ventas:
    if venta < 5000:
      alertas=alertas + 1
  #print(alertas) #Con esta función se nos imprimirá el nº de alertas
  return alertas #Con esta función se va a guardar el nº de alertas de cada lista_ventas

In [13]:
ventas_lunes=[12000,3000,8500]
ventas_martes=[4000, 1000, 25000, 45000]
alertas_lunes = auditar_ventas(ventas_lunes) #En alertas lunes se va aguardar el return de la función (alertas)
alertas_martes = auditar_ventas(ventas_martes)
print(f"El número de alertas del lunes fueron: {alertas_lunes} y el martes de {alertas_martes}")

El número de alertas del lunes fueron: 1 y el martes de 2

Limpieza de strings

In [14]:
cliente_sucio = "      pANadería PEpe  "

#Quitar espacios
cliente_sin_espacio = cliente_sucio.strip()
#Ponerlo en mayúsculas o minúsculas
cliente_mayusculas = cliente_sin_espacio.upper()
cliente_minusculas = cliente_sin_espacio.lower()
#Formato título
cliente_titulo = cliente_sin_espacio.title()

print(cliente_sucio)
print(cliente_sin_espacio)
print(cliente_mayusculas)
print(cliente_minusculas)
print(cliente_titulo)

      pANadería PEpe
pANadería PEpe
PANADERÍA PEPE
panadería pepe
Panadería Pepe

In [15]:
#Reemplazar texto
producto="Camisa_Roja_XXL"
producto_arreglado=producto.replace("_", " ")
print(producto_arreglado)

Camisa Roja XXL

Diccionarios y manejo de errores

In [16]:
#Diccionario
cliente_1 = {
    "Nombre": "Panadería Juan",
    "Ingresos": 10000,
    "VIP": True
}
cliente_1["Nombre"]
print(f"El cliente se llama {cliente_1["Nombre"]} y gana {cliente_1['Ingresos']}")

El cliente se llama Panadería Juan y gana 10000

In [22]:
#Manejo de errores
dato_corrupto="cinco mil" #Alguien lo escribio y no puso 5000

try:
  #Intentamos convertir a entero
  ingresos=int(dato_corrupto)
except ValueError:
  print("Alerta, el dato no se puede transformar")

Alerta, el dato no se puede transformar

##Librerías

Numpy

In [26]:
import numpy as np
lista=[1,2,3,4,5]
array=np.array([1,2,3,4,5])
print(lista * 2)
print(array * 2) #no los multiplica (x2) porque son vectores y (concatena los elementos)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]

Funciones dentro de numpy

In [27]:
venta_semana = np.array([1200, 1500, 900, 2100, 1800, 800, 2500 ])
#Media
media=np.mean(venta_semana)
maximo=np.max(venta_semana)
minimo=np.min(venta_semana)
desviacion_tipica=np.std(venta_semana)
print(f"La media es {round(media,2)}, el maximo es {maximo}, el minimo es {minimo} y la desviacioón típica es {round(desviacion_tipica,2)}")

La media es 1542.86, el maximo es 2500, el minimo es 800 y la desviacioón típica es 582.75

In [28]:
#Podemos filtrar muy facil
ventas_top=venta_semana[venta_semana>1500]
print(ventas_top)

[2100 1800 2500]

##Pandas

In [23]:
import pandas as pd

datos_empresa = {
    "Cliente": ["Panadería Juan", "Ferretería Luis", "Librería Paco", "Bar Centro"],
    "Ingresos": [10500, None, 8000, 20000], #¡¡Ojo al Ferretero Luis, no tenemos su dato!!
    "VIP": [True, False, False, True]
}

df = pd.DataFrame(datos_empresa)
print(datos_empresa)
print(df)

{'Cliente': ['Panadería Juan', 'Ferretería Luis', 'Librería Paco', 'Bar Centro'], 'Ingresos': [10500, None, 8000, 20000], 'VIP': [True, False, False, True]}
           Cliente  Ingresos    VIP
0   Panadería Juan   10500.0   True
1  Ferretería Luis       NaN  False
2    Librería Paco    8000.0  False
3       Bar Centro   20000.0   True

In [29]:
df["Ingresos"]

0    10500.0
1        NaN
2     8000.0
3    20000.0
Name: Ingresos, dtype: float64

In [30]:
#Para ver información técnica
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Cliente   4 non-null      object
 1   Ingresos  3 non-null      float64
 2   VIP       4 non-null      bool
dtypes: bool(1), float64(1), object(1)
memory usage: 200.0+ bytes

In [31]:
#Estadísticas descriptivas de variables numéricas
df.describe()

           Ingresos
count      3.000000
mean   12833.333333
std     6331.139971
min     8000.000000
25%     9250.000000
50%    10500.000000
75%    15250.000000
max    20000.000000

In [32]:
#Filtrar
clientes_premium = df[df["Ingresos"]>5000]
clientes_premium

          Cliente  Ingresos    VIP
0  Panadería Juan   10500.0   True
2   Librería Paco    8000.0  False
3      Bar Centro   20000.0   True

In [33]:
#Leer archivo excel
df_excel = pd.read_excel("matriculas_gradoposgrado.xlsx")

In [ ]:
df_excel #Con esto ya leo el excel completo

In [34]:
df_excel.head()

,Comunidad autónoma,Universidad,Rama,Titulación,matriculas2122,mujeres2122,matriculas2021,mujeres2021,matriculas1920,mujeres1920,matriculas1819,mujeres1819,matriculas1718,mujeres1718,matriculas1617,mujeres1617,matriculas1516,mujeres1516
0,Cataluña,Abat Oliba CEU,Ciencias Sociales y Jurídicas,Graduado o Graduada en Ciencias Políticas por ...,43,0.488372,28,0.571429,33,0.454545,29,0.310345,,,,,,
1,Cataluña,Abat Oliba CEU,Ciencias Sociales y Jurídicas,Graduado o Graduada en Criminología y Segurida...,146,0.636986,135,0.696296,116,0.698276,110,0.681818,40,0.4,43,0.325581,44,0.25
2,Cataluña,Abat Oliba CEU,Ciencias Sociales y Jurídicas,Graduado o Graduada en Derecho por la Universi...,324,0.512346,285,0.533333,250,0.54,266,0.533835,220,0.531818,197,0.548223,186,0.516129
3,Cataluña,Abat Oliba CEU,Ciencias Sociales y Jurídicas,Graduado o Graduada en Dirección de Empresas p...,237,0.383966,206,0.378641,189,0.359788,194,0.360825,92,0.304348,99,0.282828,102,0.333333
4,Cataluña,Abat Oliba CEU,Ciencias Sociales y Jurídicas,Graduado o Graduada en Economía y Gestión por ...,84,0.392857,77,0.415584,72,0.430556,63,0.444444,6,0.5,16,0.5,20,0.4